name: Build Latest

on: [push]

jobs:

  build-win:
    
    runs-on: windows-latest
    
    steps:
      
      - uses: actions/checkout@v2

      - name: Set up dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.302' 

      - run: dotnet publish -r win-x64 -c Release

      - run: dotnet publish -r win-arm64 -c Release

      - name: Upload Artifact[win-x64]
        uses: actions/upload-artifact@v1.0.0
        with:
          name: BBDown_win-x64
          path: BBDown\bin\Release\net5.0\win-x64\native\BBDown.exe

      - name: Upload Artifact[win-arm64]
        uses: actions/upload-artifact@v1.0.0
        with:
          name: BBDown_win-arm64
          path: BBDown\bin\Release\net5.0\win-arm64\native\BBDown.exe
